In [34]:
import numpy as np

#### Cancer Test Example
Let us apply Bayes' Rule to a Cancer Test Example which is a very common example in Statistic classes.
Suppose, there is a certain type of cancer which is extremely rare.

Let,
\begin{equation}
P(C) = 0.001
\end{equation}
In other words, $1$ in every $1000$ people has this cancer. Can you compute the probability of not having cancer?
\begin{equation}
P(\neg C) = 0.999
\end{equation}

The test for cancer is not $100\%$ accurate. Let us say, probability of the test being positive given someone has cancer is,
\begin{equation}
P(pos | C) = 0.8
\end{equation}
Can you compute the probability that the test is negative given someone has cancer?
\begin{equation}
P(neg | C) = 0.2
\end{equation}

Similarly, the probability of a test being positive given that someone has no cancer is $P(pos | \neg C) = 0.1$. Can you compute the probability that the test is negative given someone has no cancer?
\begin{equation}
P(neg | \neg C) = 0.9
\end{equation}

Can you compute the following?
\begin{equation}
P(C | pos) = 0.007944
\end{equation}
Interpret the quantity you computed in words!

What we computed is very interesting. We computed probability of having cancer given the test results and how likely the disease is.

In [1]:
# Modify the empty list, p, so that it becomes a UNIFORM probability
# distribution over n grid cells, as expressed in a list of 
# n probabilities.
def init_distribution(n):
    p = []
    # Add your code here
    p = n*[1/n]
    # End your code here
    return p

In [2]:
init_distribution(5)

[0.2, 0.2, 0.2, 0.2, 0.2]

In [9]:
p[red/red] = 0.75
p[green/red] = 0.25
p[red/green] = 0.25
p[green/green] = 0.75

p[x/red] = p[red/x]*p[x]/p[red]


1.875

In [161]:
#Modify the code below so that the function sense, which 
#takes p and Z as inputs, will output the normalized 
#probability distribution, q, after multiplying the entries 
# in p according to the color in the corresponding cell in world,
# followed by normalization of the probability values
world=np.array(['green', 'red', 'red', 'green', 'green'])
p = [0.2, 0.2, 0.2, 0.2, 0.2]

probs = {
    'red': {
        'green':0.25,
        'red':0.75
    },
    'green': {
        'green':0.75,
        'red':0.25
    }
}

def sense(p, Z):
    q = np.array([])
    p = np.array(p)
    # Add your code here
    for i in range(len(world)):
        q = np.append( q,  probs[world[i]][Z]*p[i] )
    
    s = sum(q)
    q = [i/s for i in q]
    # End your code here
    return q

def sense(p, Z):
    p = np.array(p)
    
        
    q = p*0 + 0.25
    q[world == Z] = 0.75
    
    q*=p
    q/=sum(q)

    # End your code here
    return q
            
sense(p, 'red')

array([0.11111111, 0.33333333, 0.33333333, 0.11111111, 0.11111111])

In [168]:
#Modify the code so that it updates the probability twice
#and gives the posterior distribution after both 
#measurements are incorporated. Make sure that your code 
#allows for any sequence of measurement of any length.

# DO NOT MODIFY THE SENSE FUNCTION. JUST CALL THE SENSE FUNCTION APPROPRIATELY

p=np.array([0.2, 0.2, 0.2, 0.2, 0.2])
world=np.array(['green', 'red', 'red', 'green', 'green'])
measurements = np.array(['red', 'green'])

# Add your code here
for i in measurements:
    p = sense(p, i)

# End your code here
print(p)

[0.04761905 0.42857143 0.42857143 0.04761905 0.04761905]


In [163]:
#Program a function that returns a new distribution 
#q, shifted to the right by U units. If U=0, q should 
#be the same as p.

def move(p, U):
  
    # ADD CODE HERE
    U = U % len(p)
    q = np.roll(p, U)
    # END CODE HERE
    return q

move([0.11, 0.33, 0.33, 0.11, 0.11], 1)

array([0.11, 0.11, 0.33, 0.33, 0.11])

In [164]:
def move_uncertain(p, U):
    
#     q = move(p,U-1)*0.1 + move(p,U)*0.8 + move(p,U+1)*0.1
    
    q = np.array([])
    n = len(p)
    for i in range(len(p)):
        q = np.append(q, p[(i-U)%n]*0.8 + p[(i-U-1)%n]*0.1 + p[(i-U+1)%n]*0.1)
    
    return q

p = np.array([0,1,0,0,0])
move_uncertain(p, 1)

array([0. , 0.1, 0.8, 0.1, 0. ])

In [165]:
p = np.array([0,1,0,0,0])

for i in range(2):
    p = move_uncertain(p, 2)
p

array([0.66, 0.16, 0.01, 0.01, 0.16])